### ISSUE TITLE
Problem building veganbagel Dockerfile

### ISSUE THREAD

**Issue by erlera123** [BrainImAccs/veganbagel#3]
Downloading build context from remote url: https://github.com/BrainImAccs/veganbagel#container:docker  154.8kB
Sending build context to Docker daemon  156.7kB
Error response from daemon: dockerfile parse error line 7: unknown instruction: <!DOCTYPE

i cannot seem to get past this point when building veganbagel. Get the same message when using a locally downloaded Dockerfile.

**Comment by crubb** [comment]
Hey erlera123,

the Dockerfile is in a separate branch at the moment (I still need to containerize fatbACPC in order to clean everything up), therefore `docker build -t veganbagel https://github.com/BrainImAccs/veganbagel.git#docker-cat12.7-standalone` _should_ work.

Unfortunately, I just noticed that the the CAT12 group has removed the standalone CAT12.7 download from their website and there is only a CAT12.8 Beta around as a standalone (http://www.neuro.uni-jena.de/cat12/). Therefore, building the Dockerfile currently won't work, even with the syntax above. I'll contact them to try and sort everything out.

Best regards,
crubb

**Comment by crubb** [comment]
Dear @erlera123,

Christian Gaser recompiled the last stable CAT 12.7 release for MCR and re-uploaded it. Please try again and let me know if you run I to any problems!

Best regards,
crumb

**Comment by erlera123** [comment]
Successfully built 79c1bd999228
Successfully tagged veganbagel:latest

Looks fine to me, now i am going to test...
Thanks a lot for your effort!
Kind regards, Andreas

-- 
Dr. med. Andreas Peter Erler
Facharzt für Radiologie
Stahmelner Höhe 7
04159 Leipzig
Tel 017627625822

Am 01.07.2021 14:57 schrieb crubb:
